// Package main is the offline measurement harness for the frozen #139 L2
// four-pair performance and correctness/A-B protocol. It implements the
// deterministic-input layer that issue #129 owns: a synthetic agent-state home
// whose inventory is fully reproducible, so the same-session paired-delta
// protocol can run with zero drift by construction and without touching a live
// home.
//
// The harness is deliberately black-box. It builds immutable base and change
// binaries from git refs via `git archive`, generates a synthetic home, runs
// `scan --json` with each binary, and compares outputs and timings. It imports
// no aibris internal package, so it compiles independently of the (unpublished)
// Codex-sessions retention provider it measures and can build the base binary
// from a tree that predates that provider.
//
// This tool does NOT publish, merge, or mutate the frozen feature branch, and
// it does not by itself close the real-home Done Criteria (DC19-21): those
// still require a quiescent real-home measurement window. It only makes that
// window short and low-risk by validating the protocol mechanics and the
// additive, non-interfering shape of the retention projection offline.
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"time"
)

// fixedFileModTime is the deterministic mtime applied to auxiliary (non-rollout)
// files so the whole synthetic home is reproducible across runs.
var fixedFileModTime = time.Date(2024, 1, 1, 0, 0, 0, 0, time.UTC)

// RolloutSpec describes one deterministic synthetic codex-sessions rollout leaf.
type RolloutSpec struct {
	// Year/Month/Day form the store path
	// <home>/.codex/sessions/<Year>/<Month>/<Day>/rollout-*.jsonl. They must be
	// a valid calendar date (the provider validates each path component).
	Year  int
	Month int
	Day   int
	// ModTime is the leaf mtime; its UTC year-month is the retention bucket the
	// provider assigns (the bucket is derived from mtime, not the directory).
	ModTime time.Time
	// Size is the exact apparent byte count of the file. The first record is
	// small; the remainder is deterministic padding the provider never reads.
	Size int64
	// CWDTgt is the recorded working directory as a path relative to the home
	// root. If it is created (listed in HomeSpec.LiveTargets) the provider
	// classifies the leaf live; otherwise the path is proven absent and the
	// leaf is classified orphaned.
	CWDTgt string
}

// NodeModuleSpec describes one synthetic node_modules directory used to give
// the base binary pre-existing inventory, so the correctness A/B can prove the
// retention change does not disturb existing rows.
type NodeModuleSpec struct {
	// RelPath is the node_modules directory relative to the home root, e.g.
	// "app/node_modules".
	RelPath string
	// Files maps a file path (relative to RelPath) to its exact byte size.
	Files map[string]int64
}

// HomeSpec describes a fully deterministic synthetic agent-state home.
type HomeSpec struct {
	Rollouts    []RolloutSpec
	LiveTargets []string
	NodeModules []NodeModuleSpec
}

// sessionMetaRecord mirrors the scalar first-record shape the Codex-sessions
// provider parses. Struct field order fixes the marshalled key order, so the
// generated bytes are deterministic.
type sessionMetaRecord struct {
	Timestamp string          `json:"timestamp"`
	Type      string          `json:"type"`
	Payload   sessionMetaBody `json:"payload"`
}

type sessionMetaBody struct {
	ID         string `json:"id"`
	CWD        string `json:"cwd"`
	Originator string `json:"originator"`
	CLIVersion string `json:"cli_version"`
}

// firstRecordLine renders the newline-terminated session_meta first record for
// a rollout leaf. The recorded cwd is absolute under the home root.
func firstRecordLine(home, cwdTgt string, idx int) ([]byte, error) {
	rec := sessionMetaRecord{
		Timestamp: "2024-01-01T00:00:00Z",
		Type:      "session_meta",
		Payload: sessionMetaBody{
			ID:         fmt.Sprintf("synth-%06d", idx),
			CWD:        filepath.Join(home, cwdTgt),
			Originator: "codex_cli_rs",
			CLIVersion: "1.2.3",
		},
	}
	b, err := json.Marshal(rec)
	if err != nil {
		return nil, err
	}
	return append(b, '\n'), nil
}

// writeRollout writes a rollout leaf of exactly max(size, len(firstLine)) bytes
// and sets its mtime, which the provider reads to assign the retention bucket.
func writeRollout(path string, firstLine []byte, size int64, modTime time.Time) error {
	n := int(size)
	if n < len(firstLine) {
		n = len(firstLine)
	}
	body := make([]byte, 0, n)
	body = append(body, firstLine...)
	if len(body) < n {
		body = append(body, bytes.Repeat([]byte{'x'}, n-len(body))...)
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(path, body, 0o644); err != nil {
		return err
	}
	return os.Chtimes(path, modTime, modTime)
}

// writeAuxFile writes a deterministic auxiliary file of exactly size bytes with
// a fixed mtime.
func writeAuxFile(path string, size int64) error {
	if size < 0 {
		size = 0
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(path, bytes.Repeat([]byte{'x'}, int(size)), 0o644); err != nil {
		return err
	}
	return os.Chtimes(path, fixedFileModTime, fixedFileModTime)
}

// Generate materializes the synthetic home under root. It is deterministic: the
// same spec produces byte-identical files with identical mtimes.
func Generate(root string, spec HomeSpec) error {
	if err := os.MkdirAll(root, 0o755); err != nil {
		return err
	}
	// A workspace directory gives every recorded cwd a nearest existing
	// ancestor that matches between live and orphan leaves, so absence proofs
	// for orphan cwds resolve identically to the live case.
	if err := os.MkdirAll(filepath.Join(root, "workspace"), 0o755); err != nil {
		return err
	}
	for _, tgt := range spec.LiveTargets {
		if err := os.MkdirAll(filepath.Join(root, tgt), 0o755); err != nil {
			return err
		}
	}
	for i, r := range spec.Rollouts {
		dir := filepath.Join(
			root, ".codex", "sessions",
			fmt.Sprintf("%04d", r.Year),
			fmt.Sprintf("%02d", r.Month),
			fmt.Sprintf("%02d", r.Day),
		)
		path := filepath.Join(dir, fmt.Sprintf("rollout-%06d.jsonl", i))
		firstLine, err := firstRecordLine(root, r.CWDTgt, i)
		if err != nil {
			return err
		}
		if err := writeRollout(path, firstLine, r.Size, r.ModTime); err != nil {
			return err
		}
	}
	for _, nm := range spec.NodeModules {
		base := filepath.Join(root, nm.RelPath)
		// Deterministic file order for stable directory state.
		rels := make([]string, 0, len(nm.Files))
		for rel := range nm.Files {
			rels = append(rels, rel)
		}
		sort.Strings(rels)
		for _, rel := range rels {
			if err := writeAuxFile(filepath.Join(base, rel), nm.Files[rel]); err != nil {
				return err
			}
		}
		if err := os.Chtimes(base, fixedFileModTime, fixedFileModTime); err != nil {
			return err
		}
	}
	return nil
}

// HomeOpts parameterizes DefaultHomeSpec.
type HomeOpts struct {
	// Months are the UTC month buckets to populate, formatted "2006-01". They
	// should all be in the past relative to the run date so no bucket is ever
	// current- or future-protected, keeping the inventory time-independent.
	Months []string
	// FilesPerMonth is the rollout count per month bucket.
	FilesPerMonth int
	// MinBytes/MaxBytes bound each rollout's apparent size (inclusive).
	MinBytes int64
	MaxBytes int64
	// LiveEvery makes one in every LiveEvery rollouts live (its cwd target is
	// created); the rest are orphaned. Zero means all orphaned.
	LiveEvery int
	// NodeModulesFiles is the number of files in the single node_modules dir
	// used for non-interference coverage. Zero defaults to 3; negative disables.
	NodeModulesFiles int
}

// DefaultHomeSpec builds a deterministic HomeSpec spanning several past month
// buckets with a controlled live/orphan split and a node_modules dir.
func DefaultHomeSpec(o HomeOpts) HomeSpec {
	if len(o.Months) == 0 {
		o.Months = []string{"2024-01", "2024-02", "2024-03", "2024-04", "2024-05", "2024-06"}
	}
	if o.FilesPerMonth <= 0 {
		o.FilesPerMonth = 8
	}
	if o.MinBytes <= 0 {
		o.MinBytes = 1024
	}
	if o.MaxBytes < o.MinBytes {
		o.MaxBytes = o.MinBytes
	}

	liveSet := make(map[string]bool)
	var rollouts []RolloutSpec
	for _, m := range o.Months {
		var y, mo int
		if _, err := fmt.Sscanf(m, "%d-%d", &y, &mo); err != nil {
			continue
		}
		for j := 0; j < o.FilesPerMonth; j++ {
			day := 1 + (j % 28)
			modTime := time.Date(y, time.Month(mo), day, 12, 0, 0, 0, time.UTC)
			var size int64
			if o.FilesPerMonth > 1 {
				size = o.MinBytes + (o.MaxBytes-o.MinBytes)*int64(j)/int64(o.FilesPerMonth-1)
			} else {
				size = o.MinBytes
			}
			var cwdTgt string
			if o.LiveEvery > 0 && j%o.LiveEvery == 0 {
				cwdTgt = fmt.Sprintf("workspace/proj-%d", j/o.LiveEvery)
				liveSet[cwdTgt] = true
			} else {
				cwdTgt = fmt.Sprintf("workspace/absent-%s-%d", m, j)
			}
			rollouts = append(rollouts, RolloutSpec{
				Year:    y,
				Month:   mo,
				Day:     day,
				ModTime: modTime,
				Size:    size,
				CWDTgt:  cwdTgt,
			})
		}
	}

	live := make([]string, 0, len(liveSet))
	for k := range liveSet {
		live = append(live, k)
	}
	sort.Strings(live)

	nmFiles := o.NodeModulesFiles
	if nmFiles == 0 {
		nmFiles = 3
	}
	spec := HomeSpec{Rollouts: rollouts, LiveTargets: live}
	if nmFiles > 0 {
		nm := NodeModuleSpec{RelPath: "app/node_modules", Files: make(map[string]int64, nmFiles)}
		for k := 0; k < nmFiles; k++ {
			nm.Files[fmt.Sprintf("pkg-%d/index.js", k)] = 4096 + int64(k)*1024
		}
		spec.NodeModules = []NodeModuleSpec{nm}
	}
	return spec
}
